name: lint
on: [push, pull_request]
jobs:
  lint-scripts:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm -v "$(pwd):/mnt" koalaman/shellcheck:v0.7.1 -x test/*.sh
